# Generated by Django 6.0.7 on 2026-07-28 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hardwaresystem_hardwarechallenge_hardwareprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardwarechallenge',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hardwarechallenge',
            name='starter_code_asm_arm',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='example_output',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LessonCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
