# Generated by Django 6.0.7 on 2026-07-29 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_hardwarechallenge_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardwarechallenge',
            old_name='starter_code_asm',
            new_name='starter_code_asm_x86',
        ),
        migrations.AlterField(
            model_name='lessoncompletion',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lesson'),
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
